name: Go
on:
  - push
jobs:
  build:
    name: Build
    strategy:
      matrix:
        platform:
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      - name: Build
        run: go build -v .
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.platform }}
          path: sops-kustomize-generator-plugin
