on:
  - push
jobs:
  build:
    name: Build
    strategy:
      matrix:
        platform:
          - macos-latest
          - ubuntu-latest
        goarch:
          - amd64
          - arm64
        exclude:
          - platform: ubuntu-latest
            goarch: arm64
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set up Go 1.24
        uses: actions/setup-go@v2.1.4
        with:
          go-version: "1.24"
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.3.4
      - name: Make
        env:
          GOARCH: ${{ matrix.goarch }}
        run: make continuous-integration
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-${{ matrix.goarch }}
          path: plugin
  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '.')
    outputs:
      upload-url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        uses: actions/create-release@v1.1.4
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
  publish-plugin:
    name: Publish Plugin
    needs: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        os:
          - name: macOS
            kernel: darwin
            goarch: amd64
          - name: macOS
            kernel: darwin
            goarch: arm64
          - name: Linux
            kernel: linux
            goarch: amd64
    steps:
      - name: Download ${{ matrix.os.name }}-${{ matrix.os.goarch }} Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.os.name }}-${{ matrix.os.goarch }}
      - name: Upload ${{ matrix.os.name }} Release Asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload-url }}
          asset_path: ./plugin
          asset_name: plugin-${{ matrix.os.kernel }}-${{ matrix.os.goarch }}
          asset_content_type: application/octet-stream
  publish-script:
    name: Publish Script
    needs:
      - release
      - publish-plugin
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out code into directory
        uses: actions/checkout@v2.3.4
      - name: Update Git Tag
        run: sed "s/v0.0.0/${GITHUB_REF##*/}/g" -i ./hack/install.sh
      - name: Upload script Release Asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload-url }}
          asset_path: ./hack/install.sh
          asset_name: install.sh
          asset_content_type: text/x-shellscript
